Repository jabardigitalservice/pikobar-rapidtest-api, pull requests merged in 2021-06, with the labels that each got.

#135 Create continuous-deployment.yml
  .github/workflows/continuous-deployment.yml
Labels: enhancement

#134 Update continuous-integration.yml
  .github/workflows/test.yml
Labels: dependencies

#180 remove unused throw
  app/Http/Controllers/Rdt/RdtEventNotifyTestResultController.php
Labels: bug

#181 Minor fixing filter sorting
  app/Http/Controllers/Rdt/RdtApplicantController.php
  app/Http/Controllers/Rdt/RdtEventController.php
Labels: bug

#183 hotfix filter date not working on end date event
  app/Http/Controllers/Rdt/RdtEventController.php
Labels: bug

#184 Up to Production minor hotfix filter date
  .github/workflows/continuous-deployment.yml
  Dockerfile
  app/Http/Controllers/Rdt/RdtEventController.php
Labels: bug

#185 add endpoint template for import result test
  app/Http/Controllers/TemplateImportResultTestController.php
  public/template/Template_Import_Tes_Result.xlsx
  routes/api.php
Labels: enhancement

#186 Add validation import excel
  app/Entities/RdtEvent.php
  app/Http/Controllers/Rdt/RdtEventController.php
  app/Http/Controllers/Rdt/RdtEventParticipantImportResultController.php
  app/Http/Requests/Rdt/RdtInvitationImportRequest.php
  app/Rules/ExcelExtensionRule.php
  app/Rules/LabResultRule.php
  resources/lang/en/validation.php
  resources/lang/id/response.php
  resources/lang/id/validation.php
  resources/lang/vendor/enum/en/validation.php
  resources/lang/vendor/enum/id/validation.php
Labels: adjustment

#187 up hotfix prod filter pikobar session id is not working properly
  app/Http/Controllers/Rdt/RdtApplicantController.php
Labels: bug

#188 Fixing structure data
  app/Http/Controllers/Rdt/RdtEventParticipantImportResultController.php
  app/Http/Requests/Rdt/RdtInvitationImportRequest.php
  app/Rules/LabResultRule.php
  resources/lang/en/validation.php
  resources/lang/id/response.php
  resources/lang/id/validation.php
Labels: adjustment

#189 Add github action sentry release workflow
  .github/workflows/continuous-deployment.yml
  app/Http/Requests/Checkin/RdtCheckinBulkRequest.php
  composer.json
  composer.lock
Labels: enhancement

#190 add minor validation to check format according template
  app/Http/Controllers/Rdt/RdtEventParticipantImportResultController.php
Labels: adjustment

#192 Up to Production 30 June 2021
  .github/workflows/continuous-deployment.yml
  .github/workflows/release-production.yml
  app/Entities/RdtEvent.php
  app/Http/Controllers/Rdt/RdtEventController.php
  app/Http/Controllers/Rdt/RdtEventParticipantImportResultController.php
  app/Http/Controllers/TemplateImportResultTestController.php
  app/Http/Requests/Checkin/RdtCheckinBulkRequest.php
  app/Http/Requests/Rdt/RdtInvitationImportRequest.php
  app/Rules/ExcelExtensionRule.php
  app/Rules/LabResultRule.php
  composer.json
  composer.lock
  public/template/Template_Import_Tes_Result.xlsx
  resources/lang/en/validation.php
  resources/lang/id/response.php
  resources/lang/id/validation.php
  resources/lang/vendor/enum/en/validation.php
  resources/lang/vendor/enum/id/validation.php
  routes/api.php
Labels: help wanted
